export const SHIFTTYPES = [
"First Shift",
"Continuing Shift",
"Final Shift",
"Days Off"
]

export const JOBSITES = [
"Brownfield",
"Odessa",
"Duncan",
"Springtown",
"San Antonio",
"Shawnee",
"Weslaco"
];

export const TECHNICIANS = ["Alaniz, Juan", 
"Andrade, Jesus", 
"Benavides, Jesus", 
"Cabrera, Sergio", 
"Camarillo, Marco", 
"Cantu, Daniel", 
"Careaga, Luis", 
"Carrion, José", 
"Cepeda, René", 
"Chavez, Javier", 
"Contreras Sr., Oscar", 
"De La Garza, Oscar", 
"De La Rosa, Irvin", 
"De León, Ricardo", 
"Elizondo, Andres", 
"Escobar, Horacio", 
"Escobedo, Arnoldo", 
"Estrada, Erick", 
"Estrada, Iovani", 
"Flores, Eric", 
"Flores, Javier", 
"Galvan, Juan", 
"Galvan, Rogelio", 
"Gaona, Daniel", 
"Garcia, Fernando", 
"Garcia, Gerardo", 
"Garcia, Louis", 
"Garza, Jesus", 
"Garza, Sergio", 
"González, Irving", 
"González, Justin", 
"González, Kevin", 
"Guerrero, Miguel", 
"Gutiérrez, Enrique", 
"Hernandez, Cesar", 
"Hernandez, Ivan", 
"Herrera, Abraham", 
"Herrera, Edgar", 
"Hisiquio, Isai", 
"Hisiquio, Sixto", 
"Iracheta, Eduardo", 
"Klimp, Billy", 
"Leal, Sergio", 
"Lopez, Raul", 
"Marquez, Lucio", 
"Marquez, Xavier Dominique", 
"Marroquin, José Luis", 
"Martinez, Gabriel", 
"Martinez, Humberto", 
"Martinez, Juan Carlos", 
"Martinez, Julio", 
"Martinez, Kevin", 
"Martinez, Pedro", 
"Martinez, Vicente", 
"Medina, Adan", 
"Medina, Calixto", 
"Medina, Daniel", 
"Medina, Francisco", 
"Medina, Miguel", 
"Mendez, José Luis", 
"Montes, Carlos", 
"Montoya, Mauricio", 
"Ocañas, Elias", 
"Ochoa, Adrian", 
"Ochoa, Armando", 
"Ochoa, Joel", 
"Osuna, José", 
"Oyervides, Arturo", 
"Palacios, Edwin", 
"Pedroza, Cristobal", 
"Peña, Advento", 
"Perales, Juan", 
"Piñon, Lauro", 
"Ramirez, Ovidio", 
"Retana, José", 
"Reyes, Gabino", 
"Reyes, Juan Manuel", 
"Rico, José", 
"Rivera, Raul", 
"Rivera, Raul Jr.", 
"Rodriguez, Antonio", 
"Rodriguez, John", 
"Rodriguez, Julio", 
"Rodriguez, Max", 
"Saldaña, Jorge", 
"Salinas, Aaron", 
"Salinas, Jesus", 
"Salinas, Saul", 
"Sanchez, Daniel", 
"Segura, Roberto", 
"Serna, Gonzalo", 
"Teniente, Juan", 
"Tijerina, René", 
"Torres, Alex", 
"Tovar, David", 
"Tovar, Eduardo", 
"Tovar, Luis", 
"Tovar, Roel", 
"Treviño, Pete", 
"Vela, Ediberto", 
"Vela, José F.", 
"Venegas, Gerardo", 
"Verduzco, Javier", 
"Villareal, Leonel", 
"Yunes, Juan Pablo", 
"Zaragoza, Juan", 
"Zuñiga, José Luis"
]